config/routes.rb
Basic::Application.routes.draw do

  resources :zoos
  resources :giraffes
  resources :zookeepers

end

app/models/giraffe.rb
class Giraffe < ActiveRecord::Base
	attr_accessible :name, :zookeeper_id
	belongs_to :zookeeper
end 

app/models/zoo.rb
class Zoo < ActiveRecord::Base
	attr_accessible :title, :place
	has_many :zookeepers
	has_many :giraffes
end 

app/models/zookeeper.rb
class Zookeeper < ActiveRecord::Base
	attr_accessible :name, :quirk, :zoo_id
	belongs_to :zoo
	has_many :giraffes
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/giraffes_controller.rb
class GiraffesController < ApplicationController
	def index 
		@giraffes = Giraffe.all 
	end 

	def show
		@giraffe = Giraffe.find(params[:id]) 
	end 

	def new 
		@giraffe = Giraffe.new
	end 

	def edit
		@giraffe = Giraffe.find(params[:id])
	end 

	def create 
		@giraffe = Giraffe.new(params[:giraffe])
		@giraffe.save 
		redirect_to @giraffe
	end 

	def update 
		@giraffe = Giraffe.find(params[:id])
	end 

	def destroy 
		@giraffe = Giraffe.find(params[:id])
		@giraffe.destroy 
		redirect_to @giraffe
	end 
end

app/controllers/zookeepers_controller.rb
class ZookeepersController < ApplicationController
	def index 
		@zookeepers = Zookeeper.all 
	end 

	def show
		@zookeeper = Zookeeper.find(params[:id]) 
	end 

	def new 
		@zookeeper = Zookeeper.new
	end 

	def edit
		@zookeeper = Zookeeper.find(params[:id])
	end 

	def create 
		@zookeeper = Zookeeper.new(params[:zookeeper])
		@zookeeper.save 
		redirect_to @zookeeper
	end 

	def update 
		@zookeeper = Zookeeper.find(params[:id])
	end 

	def destroy 
		@zookeeper = Zookeeper.find(params[:id])
		@zookeeper.destroy 
		redirect_to @zookeeper
	end 
end

app/controllers/zoos_controller.rb
class ZoosController < ApplicationController
	def index 
		@zoos = Zoo.all 
	end 

	def show
		@zoo = Zoo.find(params[:id]) 
	end 

	def new 
		@zoo = Zoo.new
	end 

	def edit
		@zoo = Zoo.find(params[:id])
	end 

	def create 
		@zoo = Zoo.new(params[:zoo])
		@zoo.save 
		redirect_to @zoo
	end 

	def update 
		@zoo = Zoo.find(params[:id])
	end 

	def destroy 
		@zoo = Zoo.find(params[:id])
		@zoo.destroy 
		redirect_to @zoo
	end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/zoos_helper.rb
module ZoosHelper
end

app/views/giraffes/_form.html.haml
= form_for @giraffe do |f|
	.field
		= f.label :name 
		= f.text_area :name
	.field 
		= f.label :zookeeper_id
		= f.number_field :zookeeper_id
	.actions
		= f.submit 'Save'

app/views/giraffes/edit.html.haml
%h1 Editing Giraffe 

= render 'form'

= link_to 'Show', @giraffe
= link_to 'Back', giraffes_path

app/views/giraffes/index.html.haml
%h1 Listing Giraffes
%table 
	%tr 
		%th Title 
		%th Place 

	- @giraffes.each do |giraffe|
		%tr 
			%td= giraffe.name
			%td= giraffe.zookeeper_id
			%td= link_to 'Show', giraffe 
			%td= link_to 'Edit', edit_giraffe_path(giraffe)
			%td= link_to 'Destroy', giraffe, :method => :delete, :data => {:confirm => 'Are you sure?'}

%br
= link_to 'New Post', new_giraffe_path

app/views/giraffes/new.html.haml
%h1 New Giraffe
= render 'form'
= link_to 'Back', giraffes_path

app/views/giraffes/show.html.haml
%ul 
	%li
		=@giraffe.name
	%li 
		=@giraffe.zookeeper_id

= link_to("delete this guy", @giraffe, :method => "delete", :confirm => "Are you sure")
=link_to("Back", giraffes_path)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basic</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zookeepers/_form.html.haml
= form_for @zookeeper do |f|
	.field
		= f.label :name 
		= f.text_area :name
	.field
		= f.label :quirk 
		= f.text_area :quirk
	.field 
		= f.label :zoo_id
		= f.number_field :zoo_id
	.actions
		= f.submit 'Save'

app/views/zookeepers/edit.html.haml
%h1 Editing Zookeeper 

= render 'form'

= link_to 'Show', @zookeeper
= link_to 'Back', zookeeper_path

app/views/zookeepers/index.html.haml
%h1 Listing Zookeepers
%table 
	%tr 
		%th Name 
		%th Quirk
		%th Zoo ID 

	- @zookeepers.each do |zookeeper|
		%tr 
			%td= zookeeper.name
			%td= zookeeper.quirk
			%td= zookeeper.zoo_id
			%td= link_to 'Show', zookeeper 
			%td= link_to 'Edit', edit_zookeeper_path(zookeeper)
			%td= link_to 'Destroy', zookeeper, :method => :delete, :data => {:confirm => 'Are you sure?'}

%br
= link_to 'New Post', new_zookeeper_path

app/views/zookeepers/new.html.haml
%h1 New Zookeepers
= render 'form'
= link_to 'Back', zookeepers_path

app/views/zookeepers/show.html.haml
%ul 
	%li
		=@zookeeper.name
	%li
		=@zookeeper.quirk
	%li 
		=@zookeeper.zoo_id

= link_to("delete this guy", @zookeeper, :method => "delete", :confirm => "Are you sure")
=link_to("Back", zookeepers_path)

app/views/zoos/_form.html.haml
= form_for @zoo do |f|
	.field
		= f.label :title 
		= f.text_area :title 
	.field 
		= f.label :place 
		= f.text_area :place
	.actions
		= f.submit 'Save'

app/views/zoos/edit.html.haml
%h1 Editing Zoos 

= render 'form'

= link_to 'Show', @zoo
= link_to 'Back', zoos_path

app/views/zoos/index.html.haml
%h1 Listing Zoos
%table 
	%tr 
		%th Title 
		%th Place 

	- @zoos.each do |zoo|
		%tr 
			%td= zoo.title 
			%td= zoo.place
			%td= link_to 'Show', zoo 
			%td= link_to 'Edit', edit_zoo_path(zoo)
			%td= link_to 'Destroy', zoo, :method => :delete, :data => {:confirm => 'Are you sure?'}

%br
= link_to 'New Post', new_zoo_path

app/views/zoos/new.html.haml
%h1 New Zoo
= render 'form'
= link_to 'Back', zoos_path

app/views/zoos/show.html.haml
%ul 
	%li
		=@zoo.title
	%li 
		=@zoo.place

= link_to("delete this guy", @zoo, :method => "delete", :confirm => "Are you sure")